### ISSUE TITLE
[minor] Variable and property naming

### ISSUE THREAD

**Issue by ale1313** [fedeemilo/rick-morty-react-challenge#3]
Regarding my previous issue, one of the things that makes your code clear is to correctly name each variable and property. Following good practices, the reader should identify and understand a variable by its name, so please be as specific as possible when doing so.

https://github.com/fedeemilo/rick-morty-react-challenge/blob/073ae1507342decb46bbf3ef5cafaab469ae044d/src/components/main/Main.js#L102

**Comment by fedeemilo** [comment]
Fixed.
