### ISSUE TITLE
[minor] Conditional rendering

### ISSUE THREAD

**Issue by ale1313** [fedeemilo/rick-morty-react-challenge#4]
When conditionally rendering some content, and specially when the block is as long as this case, please define a function which returns said components with if blocks. Later, you can use treat that function as a react component to maximize results.

https://github.com/fedeemilo/rick-morty-react-challenge/blob/073ae1507342decb46bbf3ef5cafaab469ae044d/src/components/main/Main.js#L102

**Comment by fedeemilo** [comment]
I replace the big block inside the main return for <GridOfCards /> and below <DataPagination /> components..
