### ISSUE TITLE
[suggestion] Asking if a variable exists

### ISSUE THREAD

**Issue by ale1313** [fedeemilo/rick-morty-react-challenge#5]
A good trick is using double negation to find out if a variable exists, e. g. `!!dimension` will return true if `Boolean(dimension)` is true, and false otherwise

https://github.com/fedeemilo/rick-morty-react-challenge/blob/073ae1507342decb46bbf3ef5cafaab469ae044d/src/components/utilities/card/Card.js#L32

**Comment by fedeemilo** [comment]
Suggestion added..
