### ISSUE TITLE
[minor] Returning a component depending on a boolean

### ISSUE THREAD

**Issue by ale1313** [fedeemilo/rick-morty-react-challenge#6]
You don't actually need to use a ternary to do so; referring to my previous issue, you can combine double negation with the `&&` operator to handle a conditional rendering without the need of an additional `null` returning value

https://github.com/fedeemilo/rick-morty-react-challenge/blob/073ae1507342decb46bbf3ef5cafaab469ae044d/src/components/utilities/card/Card.js#L35

**Comment by fedeemilo** [comment]
Fixed
